fix(file): remove unnecessary margin and fix error when no guiding text is provided
VilledeMontreal/angular-ui pull request #118
Opened 2023-01-18 22:11 UTC by MaudeLaflamme

![bao-file-preview_fixed](https://user-images.githubusercontent.com/33531625/213306176-576cc813-1e7d-457b-bc0a-e690ba2ff4b5.PNG)

![no-guiding-text_fixed](https://user-images.githubusercontent.com/33531625/213306220-6827391f-402b-41d8-a490-6e21f544ea98.PNG)

2023-01-19 15:05 UTC, MaudeLaflamme commented
@gregpetit C'est fait!

2023-01-19 15:19 UTC, OlivierAlbertini approved these changes

2023-01-19 15:20 UTC, OlivierAlbertini commented
ne pas oublier la PR pour master (Angular 14)

2023-01-19 17:14 UTC, gregpetit requested changes
@MaudeLaflamme J'ai mis mes commentaires dans Chromatic pour essayer. Laisse-moi savoir si c'est correct ou si tu préfères qu'on fasse ça dans GitHub comme d'habitude.

2023-01-19 17:52 UTC, sori-ard approved these changes

2023-01-19 19:30 UTC, MaudeLaflamme commented
@gregpetit C'est bien les commentaires sur Chromatic! J'y ai répondu

2023-01-20 14:18 UTC, MaudeLaflamme commented
@gregpetit Est-ce qu'il y avait d'autres changements que tu demandais, outre les bugs dans la composante Summary?

2023-01-20 15:12 UTC, gregpetit commented
Non, tout est beau!

2023-01-20 15:31 UTC, merged