Feat: Remove animation module
VilledeMontreal/angular-ui pull request #119
Opened 2023-01-19 16:03 UTC by TolaSam

Signed-off-by: TolaSam <tola.sam@montreal.ca>

2023-01-19 20:19 UTC, OlivierAlbertini commented on README.md
> -import { BaoModule } from '@villedemontreal/angular-ui';
Pourquoi l'avoir enlevé ?

2023-01-19 20:24 UTC, OlivierAlbertini approved these changes
LGTM

2023-01-19 20:26 UTC, MaudeLaflamme commented on package.json
> +  "version": "13.2.0",
Je me trompe peut-être, mais est-ce qu'on n'incrémente pas la version seulement lors des release? @OlivierAlbertini

2023-01-20 14:20 UTC, MaudeLaflamme requested changes
Remettre les lignes concernant l'importation de BaoModule dans le readme

2023-01-20 14:47 UTC, OlivierAlbertini commented on package.json
> +  "version": "13.2.0",
oui, donc la version qu'il a mis ne sera peut être pas la version qui sera publié selon les commits qu'il y a eu

2023-01-20 19:33 UTC, MaudeLaflamme approved these changes

2023-01-20 19:40 UTC, merged