feat:  Update to angular v15
VilledeMontreal/angular-ui pull request #130
Opened 2023-02-07 21:49 UTC by Ahryman40k

Bonjour, 

Veuillez trouver ici la PR en reponse au ticket #129 
Cette PR comprend 
- la mise a niveau vers Angular 15
- la mise a niveau de storybook
- la mise a niveau des autres dependences
- les commandes `npm run lint` et `npm run lint-fix` ne fonctionnaient pas et provoquaient une exception. La correction de celles-ci implique d'affecter beaucoup de heap memory pour le linting. Cela pourrait signifier un probleme sous-jacent qui ne sera pas traite ici.

Comme c'est ma premiere PR sur cette repo, merci de m'indiquer s'il existe des regles que je n'ai pas convenablement respecte.

Salutations

2023-02-08 15:18 UTC, OlivierAlbertini reviewed
LGTM. Il faudrait signer le commit car le DCO échoue (voir https://github.com/VilledeMontreal/angular-ui/blob/master/CONTRIBUTING_FR.md#certificat-dorigine-du-d%C3%A9veloppeur-dco).
Il faudrait mettre à jour la section "Versionning" dans le README pour l'ajout d'Angular 15.

Merci

2023-02-08 18:23 UTC, uelanom approved these changes

2023-02-08 19:32 UTC, Ahryman40k commented on projects/angular-ui/src/test.ts
> -const context = require.context('./', true, /\.spec\.ts$/);
dans angular.json tu trouveras
```json
 "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/angular-ui/src/test.ts",
            "tsConfig": "projects/angular-ui/tsconfig.spec.json",
            "karmaConfig": "projects/angular-ui/karma.conf.js",
            "include": [
              "**/*.spec.ts"    ///  <<<<====== ici
            ]
          }
        },
```

2023-02-08 19:34 UTC, uelanom commented on projects/angular-ui/src/test.ts
> -const context = require.context('./', true, /\.spec\.ts$/);
👍

2023-02-08 19:36 UTC, MaudeLaflamme approved these changes

2023-02-08 19:37 UTC, sori-ard approved these changes

2023-02-08 19:38 UTC, MaudeLaflamme commented on package.json
> +  "version": "15.2.0",
Pour que le check passe, oui. Tu peux squash tous tes commits en un seul et signer celui-là seulement.

2023-02-08 19:43 UTC, Ahryman40k commented on package.json
> +  "version": "15.2.0",
En fait github explique la demarche ..Donc c'est bon, merci !

2023-02-08 19:44 UTC, Ahryman40k commented on package.json
> +  "version": "15.2.0",
Les point demandes sont corriges

2023-02-09 14:28 UTC, OlivierAlbertini approved these changes

2023-02-09 14:32 UTC, OlivierAlbertini requested changes
Il faudrait régler les problèmes de lint (voir le message du build automatisé) et il y aurait aussi le package.json de la librairie à changer : https://github.com/VilledeMontreal/angular-ui/blob/master/projects/angular-ui/package.json

2023-02-09 18:39 UTC, Ahryman40k commented
> Il faudrait régler les problèmes de lint (voir le message du build automatisé) et il y aurait aussi le package.json de la librairie à changer : https://github.com/VilledeMontreal/angular-ui/blob/master/projects/angular-ui/package.json

done

2023-02-15 19:23 UTC, OlivierAlbertini approved these changes

2023-02-15 19:23 UTC, merged

2023-02-15 19:29 UTC, Ahryman40k commented
:D