feat: #54 reintroduce the snackbar
VilledeMontreal/angular-ui pull request #151
Opened 2023-03-03 16:38 UTC by mtlmatt

2023-03-14 12:43 UTC, gregpetit requested changes
Tout est beau coté design.
Coté accessibilité :

- Le aria-live="polite" devrait être pour le type succès et non info. Info et danger on un aria-live="assertive".
- Concernant le fait que cela ne fonctionne pas avec le lecteur d'écran, il faut que le contenant de ce qui va être lu dans le toast soit déjà présent dans le DOM. Ensuite, tu injectes le nouveau contenu dans ce contenant, pis à cause du aria-live, le lecteur d'écran va le lire. Plus d'info ici : https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html

2023-03-16 13:02 UTC, gregpetit approved these changes
@mtlmatt C'est fixé pour l'attribut assertive. 
Par contre, ça ne marche toujours pas avec le lecteur d'écran sur Safari alors que le code semble correct.
On va laisser passer pour l'instant.

2023-03-20 16:05 UTC, MaudeLaflamme commented on projects/angular-ui/src/lib/snack-bar/snack-bar-container.ts
> +    // TODO(crisbeto): consider de-duplicating this with the `LiveAnnouncer`.
Enlever le TODO s'il provient d'un autre codebase

2023-03-20 19:23 UTC, MaudeLaflamme approved these changes

2023-03-21 14:23 UTC, merged