feat(system-header): add system-header pattern. close #55
VilledeMontreal/angular-ui pull request #171
Opened 2023-05-24 14:29 UTC by MaudeLaflamme

![Capture d’écran, le 2023-05-24 à 10 09 57](https://github.com/VilledeMontreal/angular-ui/assets/33531625/7eba81e9-9559-4fa2-bad3-f97a45700e33)

2023-05-25 13:08 UTC, gregpetit requested changes
@MaudeLaflamme 

- La style du texte des infos supplémentaires n'est pas le bon. Ça devrait être le style "Small-Regular (font-size: 14px ; line-height : 20px)
- Sur mobile, l'info supplémentaire devrait se retrouver sous le tag, avec 4px d'espacement entre les deux (le point de séparation n'est plus présent).

2023-05-25 13:22 UTC, MaudeLaflamme commented
@gregpetit 
C'est noté pour le style du texte d'info supplémentaires.
Pour ton deuxième point, tu veux dire que lorsque tu passes à mobile, l'info supplémentaire ne va pas sous le tag?
![image](https://github.com/VilledeMontreal/angular-ui/assets/33531625/fb9efbe3-3c3b-410b-9563-ea57e1e7df23)

2023-05-25 14:06 UTC, OlivierAlbertini approved these changes
LGTM

2023-05-26 18:11 UTC, gregpetit approved these changes

2023-05-26 18:38 UTC, merged