docs: updating readme
VilledeMontreal/angular-ui pull request #174
Opened 2023-06-09 19:36 UTC by OlivierAlbertini

also adding english version like other repos

2023-06-12 13:07 UTC, uelanom approved these changes

2023-06-12 13:19 UTC, sori-ard approved these changes

2023-06-12 13:24 UTC, MaudeLaflamme commented on CONTRIBUTING_FR.md
> +1. Regarder si le component existe déjà ou si quelqu'un travail déjà sur celui-ci.
Regarder si la composante existe déjà ou si quelqu'un travaille déjà sur celle-ci.

2023-06-12 13:35 UTC, MaudeLaflamme requested changes

2023-06-12 13:35 UTC, MaudeLaflamme commented on CONTRIBUTING_FR.md
> +4. Produire le component conformément au niveau de qualité et avec l'approche de [Material Angular](https://material.angular.io/).
Produire LA COMPOSANTE conformément...

2023-06-12 13:35 UTC, MaudeLaflamme commented on CONTRIBUTING_FR.md
> +8. Une fois la PR approuvé par au moins deux des maintainers, le travail est terminé! Une nouvelle version de la lib est sur le point d'être released!
Une fois la PR approuvée par au moins deux des MAINTENEURS, le travail est terminé ! Une nouvelle version de la librairie est sur le point d'être publiée !

2023-06-12 13:35 UTC, MaudeLaflamme commented on CONTRIBUTING_FR.md
> +9. Upgrader la version de la lib où nécessaire et apprécier un travail bien fait et standard qui sera utiliser par tous 💗 !
Mettre à jour la version de la librairie où nécessaire et apprécier un travail bien fait et standard qui sera utilisÉ par tous !

2023-06-12 13:35 UTC, MaudeLaflamme commented on README.md
> +- Code examples is available [here](https://services.interne.montreal.ca/bao-storybook).
Code examples ARE available

2023-06-12 13:35 UTC, MaudeLaflamme commented on README.md
> +When possible we want to leave the developer free to compose the content of his component as he wishes.
... to compose the content of THEIR component as THEY wish (pronon non genré puisque les contributeurs ne sont pas que des hommes ;) )

2023-06-12 13:35 UTC, MaudeLaflamme commented on README_FR.md
> +Codes-tu avec le style ? Oui ? OK, "you rock"! 🎸 Sinon, nous pouvons t'aider à démarrer avec [la documentation, les démos et les guides](https://zeroheight.com/575tugn0n/p/261b21-avant-utilisation)!
Codes-tu avec ~le~ style ?

2023-06-13 18:41 UTC, MaudeLaflamme approved these changes

2023-06-13 20:58 UTC, merged