fix: Issue-63 : Add the possibility to override Alert texts
VilledeMontreal/angular-ui pull request #208
Opened 2024-05-30 18:24 UTC by TolaSam

2024-05-31 12:50 UTC, gregpetit requested changes
@TolaSam Le mécanisme fonctionne mais il y a une erreur dans l'exemple "Primary".
Le texte de l'icône lu par le lecteur d'écran est "Warning" alors que ça devrait être "Information".
TOut est beau pour le reste.

2024-05-31 14:25 UTC, MaudeLaflamme approved these changes
Juste adresser le commentaire de Greg et c'est bon pour moi !

2024-06-06 15:18 UTC, gregpetit approved these changes
Tout est beau. Le petit problème a été fixé.

2024-06-06 16:17 UTC, TolaSam commented
Add the possibility to translate texts on Alert component.

2024-06-06 18:05 UTC, merged