feat: crmmon-7566 - Add a dropdown menu as a list item option
VilledeMontreal/angular-ui pull request #214
Opened 2024-08-21 17:22 UTC by TolaSam

2024-08-22 13:02 UTC, gregpetit requested changes
@TolaSam 
Au niveau du UI, tout est beau.
Il y a un problème au niveau de la navigation clavier par contre.
Quand je rentre dans le menu en appuyant sur ENTER ou SPACE, quand j'appuie ensuite sur la flèche du bas pour accéder au premier élément du menu, c'est toujours le second élément du menu qui se sélectionne, au lieu du premier.
Laisse-moi savoir si tu veux que je te montre.

2024-08-26 19:55 UTC, gregpetit approved these changes
@TolaSam Tout est beau!

2024-08-27 22:56 UTC, MaudeLaflamme commented on projects/storybook-angular/src/stories/DropdownMenu/DropdownMenu.stories.ts
Est-ce que les changements sur ce fichier de tests sont nécessaires ? C'est la story du DropdownMenu directement, pas celle de la liste

2024-08-27 22:56 UTC, MaudeLaflamme commented on projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts
> -  @HostListener('window:keyup.enter', ['$event'])
Ça fait partie des spécifications de la composante Dropdown menu que lorsque le menu est ouvert via le clavier, le focus se met sur le premier item activable du menu. Ce n'est plus le cas si tu retires cette fonction, le menu s'ouvre, mais aucun item ne reçoit le focus

2024-08-29 16:09 UTC, TolaSam commented on projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts
> -  @HostListener('window:keyup.enter', ['$event'])
Exact, c'est voulu selon l'équipe d'accessibilité. Il n'y a pas de focus au premier élément lorsque le menu s'ouvre.

2024-08-29 17:14 UTC, TolaSam commented on projects/storybook-angular/src/stories/DropdownMenu/DropdownMenu.stories.ts
En fait, c'était pour les tests et je les garder ainsi. Il y avait des défauts au niveau de la navigation par flèche. Là tout est corrigé.

2024-08-29 19:59 UTC, MaudeLaflamme approved these changes

2024-08-29 20:08 UTC, merged