feat(hyperlink): add bao-hyperlink component. close #86
VilledeMontreal/angular-ui pull request #87
Opened 2022-10-26 21:10 UTC by MaudeLaflamme

Signed-off-by: Maude LAFLAMME <maude.laflamme@montreal.ca>

![hyperlink1](https://user-images.githubusercontent.com/33531625/198138439-6fdace6b-fdcd-433a-96dd-8e96c1be4eaa.PNG)
![hyperlink2](https://user-images.githubusercontent.com/33531625/198138450-4e500986-908b-45a4-ac1f-3aaf33aa3162.PNG)

2022-10-27 12:13 UTC, gregpetit commented
@MaudeLaflamme Peux-tu faire un build dans Chromatic pour que je puisse faire ma review?

2022-10-27 13:03 UTC, MaudeLaflamme commented
@gregpetit c'est fait!

2022-10-27 13:11 UTC, OlivierAlbertini approved these changes
👍

2022-10-27 13:16 UTC, OlivierAlbertini commented on projects/storybook-angular/src/stories/Hyperlink/Hyperlink.stories.ts
> +        <a href=#> a hyperlink!</a>
le size n'est pas binder et du coup quand on change la taille sur le contrôle dans storybook, ça ne change pas la taille du lien

2022-10-27 13:18 UTC, OlivierAlbertini requested changes
binder le contrôle pour pouvoir changer la taille du lien

2022-10-27 13:26 UTC, MaudeLaflamme commented on projects/storybook-angular/src/stories/Hyperlink/Hyperlink.stories.ts
> +        <a href=#> a hyperlink!</a>
Lorsque le lien est dans un texte, il prend la taille du texte, le input "size" n'est pas appliqué. C'est seulement dans une liste de liens qu'on peut contrôler la taille avec le input. Donc le contrôle dans storybook ne sert à rien dans ce cas. Penses-tu que je devrais mettre une liste de liens plutôt qu'un lien _inline_, pour pouvoir tester le input?

2022-10-27 13:30 UTC, OlivierAlbertini commented on projects/storybook-angular/src/stories/Hyperlink/Hyperlink.stories.ts
> +        <a href=#> a hyperlink!</a>
oui, car on veut tester l'hyperlien dans cette story, tu peux mettre un exemple avec le texte en dessous et décrire que le lien ne prendra pas le size, c'est bon à savoir.

2022-10-27 13:50 UTC, gregpetit commented
@MaudeLaflamme 
Plusieurs petits problèmes :
1. Pour les versions inline dans les 2 premiers exemples, le font size est de 16px, et le line-height de 28px. Ce n,est pas une combinaison qu'on supporte. Le style medium est 16px avec un line-height de 24px. Ça fait que le souligné du lien apparait trop bas, avec même un pixel en trop è cause de la ligne (voir problème 3).
2. Pour la taille small (seulement visible dans l'exemple avec les liste), la taille de l'icône est trop grande. Elle devrait être de 20px x 20px. Ce n'est pas une taille standard mais ça match le line-height du style de font small.
3. Dans les listes, il y a un effet de décalage minimum qui apparait lors du hover. Je pense que c'est parce que la ligne ajoute un pixel sur la hauteur de la composante, alors que cela ne devrait pas. Dans figma, la bordure est interne donc la hauteur de la composante reste la même que la ligne soit présente ou pas.

2022-10-27 14:28 UTC, MaudeLaflamme commented
@gregpetit

> Ce n'est pas une taille standard mais ça match le line-height du style de font small.

Donc je ne dois pas utiliser les tailles préexistantes de la composante bao-icon? Je fixe les dimensions de l'icône selon le line-height du texte? Même chose dans le cas d'un hyperlien inline avec icône?

2022-10-27 14:30 UTC, MaudeLaflamme commented
@gregpetit 

> Ce n'est pas une taille standard mais ça match le line-height du style de font small.

Donc je ne dois pas utiliser les tailles préexistantes de la composante bao-icon? Je fixe les dimensions de l'icône selon le line-height du texte? Même chose dans le cas d'un hyperlien inline avec icône qui hérite de la taille du texte dans lequel il se trouve?

2022-10-27 17:43 UTC, gregpetit commented
@MaudeLaflamme Ça peut être façon de faire sachant qu'on va normalement juste utiliser les tailles medium, small, et XSmall pour les liens, et la taille des icones match le line-height du style de texte correspondant.

2022-10-27 21:19 UTC, OlivierAlbertini approved these changes

2022-10-28 13:25 UTC, MaudeLaflamme commented
@gregpetit Les changements ont été apportés et le build dans Chromatic a été mis à jour

2022-10-28 19:48 UTC, gregpetit commented
> @gregpetit Les changements ont été apportés et le build dans Chromatic a été mis à jour
@MaudeLaflamme 
Tout est beau. 
Est ce qu'on peut juste mettre le line-height à 24px dans le premier exemple (Primary) pour que ça soit un style de police standard?

2022-10-28 20:19 UTC, MaudeLaflamme commented
@gregpetit Oui c'est changé

2022-10-31 12:12 UTC, gregpetit approved these changes
Tout est beau!
Merci @MaudeLaflamme

2022-10-31 13:14 UTC, MaudeLaflamme commented
@OlivierAlbertini @gregpetit est-ce que l'un de vous peut approuver les changements sur Chromatic? Merci!

2022-10-31 13:57 UTC, gregpetit commented
> @OlivierAlbertini @gregpetit est-ce que l'un de vous peut approuver les changements sur Chromatic? Merci!

C'est fait!

2022-10-31 14:06 UTC, merged