feat(dropdown-menu): add dropdown-menu component. close #50
VilledeMontreal/angular-ui pull request #91
Opened 2022-11-11 16:41 UTC by MaudeLaflamme

![dropdown_menu1](https://user-images.githubusercontent.com/33531625/201387647-cca1a09b-b32d-42d2-abff-35504c1820d9.png)

![dropdown_menu2](https://user-images.githubusercontent.com/33531625/201387676-77ee8d07-1902-4840-bbca-5fde15f53c74.png)

![dropdown_menu3](https://user-images.githubusercontent.com/33531625/201387693-7e3522d2-cb53-4060-9235-ed09421c6845.png)

2022-11-11 21:01 UTC, gregpetit requested changes
@MaudeLaflamme 
Quelques changements:
1. Il manque un padding top et bottom (8px ou 0.5rem) au container du menu.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/100230904/201426694-7fd890a9-d896-47ce-818c-4eff448f71eb.png">
2. Il y a un espacement de trop pour les checkbox et les boutons radio ce qui fait que la largeur de l'endroit où est le bouton radio ou la checkbox est de 32px, alors qu'il devrait être de 24px.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/100230904/201427627-2c3a7638-056a-423d-993f-0c1a6f91408c.png">
3. Les titres de section ont un margin-top de 8px (ce qui est bon), mais ils devraient aussi avoir un margin-bottom de 8px.
4. Le divider devrait avoir un margin-top et margin-bottom de 8px, alors qu'il est présentement de 16px.
5. Pour les versions checkbox et bouton radio, le click ou le déclenchement via le clavier de l'ensemble de l'item du menu devrait changer son statut (coché ou non). Présentement, seul le click sur la checkbox ou le bouton radio effectue ce changement.
6. L'ID du menu semble être mal défini, ce qui fait que la référence ario-controls ne fonctionne pas
<img width="420" alt="Capture d’écran, le 2022-11-11 à 15 53 39" src="https://user-images.githubusercontent.com/100230904/201429164-d8f83c19-ca27-4627-8106-dbc83b8e8d68.png">
7. Quand le menu est caché, il est caché du DOM alors que cela ne devrait pas être le cas. Il devrait par contre avoir un aria-expanded="true"
8. L'activation d'un item via le clavier ne semble pas fonctionner (Scénario "Activer un item via le clavier" dans les specs d'accessibilité_

Ajouter les exemple suivant :
* Où le menu apparait au-dessus du déclencheur (dans le cas où le déclencheur est en bas de l'écran)
* Où le menu est utilisé comme menu de navigation, avec un élément sélectionné par défaut, afin de voir aria-current="page" en action

2022-11-16 21:00 UTC, gregpetit commented
@MaudeLaflamme 
Comme discuter : 
1. Fixer l'espacement entre le bord droit, l'élément graphique (avatar, icone, radio/checkbox) et le contenu. Il devrait être de 16px
2. Fixer l'espacement entre le séparateur et le titre
3. Montrer l'exemple d'un élément du menu qui est sélectionné quand le menu est en mode navigation

2022-11-17 13:15 UTC, gregpetit approved these changes

2022-11-17 20:22 UTC, MaudeLaflamme commented
@OlivierAlbertini Je vais ajouter isClosedByKeyEvent, je pense que ça peut être utile pour les développeurs de savoir que la composante émet des outputs.

2022-11-18 14:19 UTC, merged

2022-11-18 18:19 UTC, sori-ard commented
Le checkbox quand on click il n'ont pas l'air de marcher.

2022-11-18 18:26 UTC, gregpetit commented
@MaudeLaflamme Sorina a raison. Je n,avais pas vu ça... Ça marche qu'on on clique sur le libellé de la checkbox mais pas sur la checkbox en elle-même...
Ça marche correctent pour les boutons radios par contre...

2022-11-18 18:45 UTC, MaudeLaflamme commented
@sori-ard @gregpetit  Ok je regarde ça!